# Services needed: 
#   - mariadb: database service for wp
#   - nginx: web server for serving WP with https
#   - wordpress: application container running wordpress with php-fpm
# Volume and Network:
#   - VOLUME: Persistent storage for mariadb and WP files
#   - NETWORK: bridge network between containers!!!
# version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    env_file:
      .env
    # environment:
    #   - MYSQL_DATABASE=${MYSQL_DATABASE}
    #   - MYSQL_USER=${MYSQL_USER}
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    # expose:
    #   - "3306" #internal connection between containers

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      - wordpress # depends-on make sure WP starts before Nginx!!!
    # env_file:
    #   - .env
    # environment:
    #   - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/html # mount wp files
    restart: always
    ports:
      - "443:443"
      # <HOST_PORT>:<CONTAINER_PORT> map 443 on the host to port 443 for HTTPS
      # 443: extenal port on VM: https//server-ip:443
      # 443 (right) : internally (inside container), nginx listen on 443
  
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      - mariadb # mariadb starts before wp
        # condition: service_healthy
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always
    # environment:
    #   - DOMAIN_NAME=${DOMAIN_NAME}
    #   - WORDPRESS_DB_HOST=${WP_DB_HOST}
    #   - WORDPRESS_DB_USER=${WP_DB_USER}
    #   - WORDPRESS_DB_NAME=${WP_DB_NAME}
    #   - WORDPRESS_TITLE=${WP_TITLE}
    #   - WORDPRESS_ADMIN=${WP_ADMIN}
    #   - WORDPRESS_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    #   - WORDPRESS_REGULAR_USER=${WP_REGULAR_USER}
    #   - WORDPRESS_REGULAR_EMAIL=${WP_REGULAR_EMAIL}
    # healthcheck:
    #   test: ["CMD-SHELL", "nc -z localhost 9000"]
    #   interval: 20s
    #   timeout: 15s
    #   retries: 10
    #   start_period: 10s

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ewu/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ewu/data/wordpress

networks:
  inception:
    name: inception

# bridge: default driver for standalne containers, create isolated network on Docker host
# host: rmv network isolation between containers and Docker host, directly share
# none: completely isolate container from network, no External Nor internal connect possible
# Custom Network: the network 'inception' is the customized network i invented
#  => isolate external connection, allow INTERNAL connection between containars
# 